apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  labels:
    app: policy-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: randyhokl/policy-service:33334f63041e2eef1779d1627ef4b1919b2b8349
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8082
