apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  labels:
    app: policy-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: randyhokl/policy-service:f432ab7090da7b851235e075a1a32ce72834fd6f
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8082
